### Numpy
Numpy is a fundamental library for scientific computing in Python. It provides support for Arrays and matrices,along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of Numpy, focusing on arrays and vectprized operations.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.1.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

# create arrays using numpy
## Create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [7]:
type(arr1)

numpy.ndarray

In [8]:
print(arr1.shape)

(5,)


In [10]:
# 1D Array
arr2=np.array([1,2,3,4,5]) 
print(arr2.reshape(1,5))  # 1 row and 5 coloumns

[[1 2 3 4 5]]


In [12]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [15]:
# 2D Array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [19]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
## Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape: ",arr.shape)
print("No of Dimensions :",arr.ndim)
print("Size(Number of elements): ",arr.size)
print("Data Type: ",arr.dtype)
print("Item size (in bytes): ",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
No of Dimensions : 2
Size(Number of elements):  6
Data Type:  int64
Item size (in bytes):  8


In [26]:
# Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element Wise Addition
print("Addition:",arr1+arr2)

## Element Wise Substraction
print("Substraction:",arr1-arr2)

## Element Wise Multiplication
print("Multiplication:",arr1*arr2)

## Element Wise Division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [32]:
## Universal Functions
arr = np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

# Exonential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [37]:
## Array slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
print(arr[0][1])

2


In [41]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [46]:
print(arr[0:2,3:])

[[4]
 [8]]


In [55]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [56]:
## Modify the Array Elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [58]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [61]:
## Statistical Concept -- Normalization
## To have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and Standard deviation
mean = np.mean(data)
std_dev = np.std(data)

print(mean,std_dev)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:",normalized_data)

3.0 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [64]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:",mean)

# median
median = np.median(data)
print("median:",median)

# Standard deviation
std_dev = np.std(data)
print("Standard deviation:",std_dev)

# Variance
variance = np.var(data)
print("Variance: ",variance)

Mean: 5.5
median: 5.5
Standard deviation: 2.8722813232690143
Variance:  8.25


In [67]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
data[data>5]


[False False False False False  True  True  True  True  True]


array([ 6,  7,  8,  9, 10])

In [75]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])